// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/phone/phone.proto

package phone

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,2,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePhoneRequest) Reset() {
	*x = CreatePhoneRequest{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneRequest) ProtoMessage() {}

func (x *CreatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneRequest.ProtoReflect.Descriptor instead.
func (*CreatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreatePhoneRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreatePhoneRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreatePhoneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePhoneReply) Reset() {
	*x = CreatePhoneReply{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhoneReply) ProtoMessage() {}

func (x *CreatePhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhoneReply.ProtoReflect.Descriptor instead.
func (*CreatePhoneReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePhoneReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePhoneReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreatePhoneReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreatePhoneReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePhoneReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreatePhoneReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdatePhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhoneRequest) Reset() {
	*x = UpdatePhoneRequest{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneRequest) ProtoMessage() {}

func (x *UpdatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePhoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdatePhoneRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdatePhoneRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdatePhoneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhoneReply) Reset() {
	*x = UpdatePhoneReply{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneReply) ProtoMessage() {}

func (x *UpdatePhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneReply.ProtoReflect.Descriptor instead.
func (*UpdatePhoneReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePhoneReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePhoneReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdatePhoneReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdatePhoneReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdatePhoneReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdatePhoneReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeletePhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhoneRequest) Reset() {
	*x = DeletePhoneRequest{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhoneRequest) ProtoMessage() {}

func (x *DeletePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhoneRequest.ProtoReflect.Descriptor instead.
func (*DeletePhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePhoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeletePhoneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePhoneReply) Reset() {
	*x = DeletePhoneReply{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhoneReply) ProtoMessage() {}

func (x *DeletePhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhoneReply.ProtoReflect.Descriptor instead.
func (*DeletePhoneReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePhoneReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhoneRequest) Reset() {
	*x = GetPhoneRequest{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhoneRequest) ProtoMessage() {}

func (x *GetPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhoneRequest.ProtoReflect.Descriptor instead.
func (*GetPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{6}
}

func (x *GetPhoneRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPhoneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPhoneReply) Reset() {
	*x = GetPhoneReply{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPhoneReply) ProtoMessage() {}

func (x *GetPhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPhoneReply.ProtoReflect.Descriptor instead.
func (*GetPhoneReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{7}
}

func (x *GetPhoneReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPhoneReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetPhoneReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *GetPhoneReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetPhoneReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetPhoneReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhoneRequest) Reset() {
	*x = ListPhoneRequest{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhoneRequest) ProtoMessage() {}

func (x *ListPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhoneRequest.ProtoReflect.Descriptor instead.
func (*ListPhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{8}
}

func (x *ListPhoneRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListPhoneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listphones    []*PhoneList           `protobuf:"bytes,1,rep,name=listphones,proto3" json:"listphones,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPhoneReply) Reset() {
	*x = ListPhoneReply{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhoneReply) ProtoMessage() {}

func (x *ListPhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhoneReply.ProtoReflect.Descriptor instead.
func (*ListPhoneReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{9}
}

func (x *ListPhoneReply) GetListphones() []*PhoneList {
	if x != nil {
		return x.Listphones
	}
	return nil
}

func (x *ListPhoneReply) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PhoneList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. mobile, home, work
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneList) Reset() {
	*x = PhoneList{}
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneList) ProtoMessage() {}

func (x *PhoneList) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_phone_phone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneList.ProtoReflect.Descriptor instead.
func (*PhoneList) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_phone_phone_proto_rawDescGZIP(), []int{10}
}

func (x *PhoneList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PhoneList) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneList) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *PhoneList) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PhoneList) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PhoneList) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_helloworld_v1_phone_phone_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_phone_phone_proto_rawDesc = "" +
	"\n" +
	"#api/helloworld/v1/phone/phone.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"]\n" +
	"\x12CreatePhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x02 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xa9\x01\n" +
	"\x10CreatePhoneReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"m\n" +
	"\x12UpdatePhoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xa9\x01\n" +
	"\x10UpdatePhoneReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"$\n" +
	"\x12DeletePhoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\",\n" +
	"\x10DeletePhoneReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x0fGetPhoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xa6\x01\n" +
	"\rGetPhoneReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"&\n" +
	"\x10ListPhoneRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\"d\n" +
	"\x0eListPhoneReply\x12<\n" +
	"\n" +
	"listphones\x18\x01 \x03(\v2\x1c.api.helloworld.v1.PhoneListR\n" +
	"listphones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\xa2\x01\n" +
	"\tPhoneList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt2\xbf\x04\n" +
	"\fPhoneService\x12o\n" +
	"\vCreatePhone\x12%.api.helloworld.v1.CreatePhoneRequest\x1a#.api.helloworld.v1.CreatePhoneReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/phone\x12t\n" +
	"\vUpdatePhone\x12%.api.helloworld.v1.UpdatePhoneRequest\x1a#.api.helloworld.v1.UpdatePhoneReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/phone/{id}\x12q\n" +
	"\vDeletePhone\x12%.api.helloworld.v1.DeletePhoneRequest\x1a#.api.helloworld.v1.DeletePhoneReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/phone/{id}\x12h\n" +
	"\bGetPhone\x12\".api.helloworld.v1.GetPhoneRequest\x1a .api.helloworld.v1.GetPhoneReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/phone/{id}\x12k\n" +
	"\tListPhone\x12#.api.helloworld.v1.ListPhoneRequest\x1a!.api.helloworld.v1.ListPhoneReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/phone/listBN\n" +
	"\x17api.helloworld.v1.phoneP\x01Z1customer-management/api/helloworld/v1/phone;phoneb\x06proto3"

var (
	file_api_helloworld_v1_phone_phone_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_phone_phone_proto_rawDescData []byte
)

func file_api_helloworld_v1_phone_phone_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_phone_phone_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_phone_phone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_phone_phone_proto_rawDesc), len(file_api_helloworld_v1_phone_phone_proto_rawDesc)))
	})
	return file_api_helloworld_v1_phone_phone_proto_rawDescData
}

var file_api_helloworld_v1_phone_phone_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_helloworld_v1_phone_phone_proto_goTypes = []any{
	(*CreatePhoneRequest)(nil), // 0: api.helloworld.v1.CreatePhoneRequest
	(*CreatePhoneReply)(nil),   // 1: api.helloworld.v1.CreatePhoneReply
	(*UpdatePhoneRequest)(nil), // 2: api.helloworld.v1.UpdatePhoneRequest
	(*UpdatePhoneReply)(nil),   // 3: api.helloworld.v1.UpdatePhoneReply
	(*DeletePhoneRequest)(nil), // 4: api.helloworld.v1.DeletePhoneRequest
	(*DeletePhoneReply)(nil),   // 5: api.helloworld.v1.DeletePhoneReply
	(*GetPhoneRequest)(nil),    // 6: api.helloworld.v1.GetPhoneRequest
	(*GetPhoneReply)(nil),      // 7: api.helloworld.v1.GetPhoneReply
	(*ListPhoneRequest)(nil),   // 8: api.helloworld.v1.ListPhoneRequest
	(*ListPhoneReply)(nil),     // 9: api.helloworld.v1.ListPhoneReply
	(*PhoneList)(nil),          // 10: api.helloworld.v1.PhoneList
}
var file_api_helloworld_v1_phone_phone_proto_depIdxs = []int32{
	10, // 0: api.helloworld.v1.ListPhoneReply.listphones:type_name -> api.helloworld.v1.PhoneList
	0,  // 1: api.helloworld.v1.PhoneService.CreatePhone:input_type -> api.helloworld.v1.CreatePhoneRequest
	2,  // 2: api.helloworld.v1.PhoneService.UpdatePhone:input_type -> api.helloworld.v1.UpdatePhoneRequest
	4,  // 3: api.helloworld.v1.PhoneService.DeletePhone:input_type -> api.helloworld.v1.DeletePhoneRequest
	6,  // 4: api.helloworld.v1.PhoneService.GetPhone:input_type -> api.helloworld.v1.GetPhoneRequest
	8,  // 5: api.helloworld.v1.PhoneService.ListPhone:input_type -> api.helloworld.v1.ListPhoneRequest
	1,  // 6: api.helloworld.v1.PhoneService.CreatePhone:output_type -> api.helloworld.v1.CreatePhoneReply
	3,  // 7: api.helloworld.v1.PhoneService.UpdatePhone:output_type -> api.helloworld.v1.UpdatePhoneReply
	5,  // 8: api.helloworld.v1.PhoneService.DeletePhone:output_type -> api.helloworld.v1.DeletePhoneReply
	7,  // 9: api.helloworld.v1.PhoneService.GetPhone:output_type -> api.helloworld.v1.GetPhoneReply
	9,  // 10: api.helloworld.v1.PhoneService.ListPhone:output_type -> api.helloworld.v1.ListPhoneReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_phone_phone_proto_init() }
func file_api_helloworld_v1_phone_phone_proto_init() {
	if File_api_helloworld_v1_phone_phone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_phone_phone_proto_rawDesc), len(file_api_helloworld_v1_phone_phone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_phone_phone_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_phone_phone_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_phone_phone_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_phone_phone_proto = out.File
	file_api_helloworld_v1_phone_phone_proto_goTypes = nil
	file_api_helloworld_v1_phone_phone_proto_depIdxs = nil
}
