// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"customer-management/internal/biz"
	"customer-management/internal/conf"
	"customer-management/internal/data"
	"customer-management/internal/server"
	"customer-management/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	customerRepository := data.NewCustomerRepository(dataData)
	customerbiz := biz.NewCustomerBiz(customerRepository)
	customerService := service.NewCustomerService(customerbiz)
	emailRepository := data.NewEmailRepository(dataData)
	emailbiz := biz.NewEmailbiz(emailRepository)
	emailService := service.NewEmailService(emailbiz)
	phoneRepository := data.NewPhoneRepository(dataData)
	phonebiz := biz.NewPhonebiz(phoneRepository)
	phoneService := service.NewPhoneService(phonebiz)
	addressRepository := data.NewAddressRepository(dataData)
	addressbiz := biz.NewAddressBiz(addressRepository)
	addressService := service.NewAddressService(addressbiz)
	grpcServer := server.NewGRPCServer(confServer, customerService, emailService, phoneService, addressService, logger)
	httpServer := server.NewHTTPServer(confServer, customerService, emailService, phoneService, addressService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
