// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/email.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailRequest) Reset() {
	*x = CreateEmailRequest{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailRequest) ProtoMessage() {}

func (x *CreateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmailRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateEmailRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type CreateEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmailReply) Reset() {
	*x = CreateEmailReply{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailReply) ProtoMessage() {}

func (x *CreateEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailReply.ProtoReflect.Descriptor instead.
func (*CreateEmailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmailReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateEmailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmailReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateEmailReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *CreateEmailReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateEmailReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Userid        uint32                 `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateEmailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmailRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateEmailRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdateEmailRequest) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type UpdateEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Userid        uint32                 `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailReply) Reset() {
	*x = UpdateEmailReply{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailReply) ProtoMessage() {}

func (x *UpdateEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailReply.ProtoReflect.Descriptor instead.
func (*UpdateEmailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateEmailReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmailReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateEmailReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdateEmailReply) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UpdateEmailReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UpdateEmailReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailRequest) Reset() {
	*x = DeleteEmailRequest{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailRequest) ProtoMessage() {}

func (x *DeleteEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteEmailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmailReply) Reset() {
	*x = DeleteEmailReply{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailReply) ProtoMessage() {}

func (x *DeleteEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailReply.ProtoReflect.Descriptor instead.
func (*DeleteEmailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEmailReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Userid        uint32                 `protobuf:"varint,2,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmailRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmailRequest) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type GetEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Userid        uint32                 `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailReply) Reset() {
	*x = GetEmailReply{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailReply) ProtoMessage() {}

func (x *GetEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailReply.ProtoReflect.Descriptor instead.
func (*GetEmailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmailReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmailReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetEmailReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetEmailReply) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *GetEmailReply) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *GetEmailReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetEmailReply) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        uint32                 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailRequest) Reset() {
	*x = ListEmailRequest{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailRequest) ProtoMessage() {}

func (x *ListEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailRequest.ProtoReflect.Descriptor instead.
func (*ListEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{8}
}

func (x *ListEmailRequest) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

type ListEmailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*Emails              `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailReply) Reset() {
	*x = ListEmailReply{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailReply) ProtoMessage() {}

func (x *ListEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailReply.ProtoReflect.Descriptor instead.
func (*ListEmailReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{9}
}

func (x *ListEmailReply) GetEmails() []*Emails {
	if x != nil {
		return x.Emails
	}
	return nil
}

type Emails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	Userid        uint32                 `protobuf:"varint,5,opt,name=userid,proto3" json:"userid,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emails) Reset() {
	*x = Emails{}
	mi := &file_api_helloworld_v1_email_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emails) ProtoMessage() {}

func (x *Emails) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_email_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emails.ProtoReflect.Descriptor instead.
func (*Emails) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_email_proto_rawDescGZIP(), []int{10}
}

func (x *Emails) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Emails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Emails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Emails) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Emails) GetUserid() uint32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *Emails) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Emails) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_helloworld_v1_email_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_email_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/email.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"]\n" +
	"\x12CreateEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\"\xa9\x01\n" +
	"\x10CreateEmailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x85\x01\n" +
	"\x12UpdateEmailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x16\n" +
	"\x06userid\x18\x05 \x01(\rR\x06userid\"\xc1\x01\n" +
	"\x10UpdateEmailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x16\n" +
	"\x06userid\x18\x05 \x01(\rR\x06userid\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"$\n" +
	"\x12DeleteEmailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\",\n" +
	"\x10DeleteEmailReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"9\n" +
	"\x0fGetEmailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\rR\x06userid\"\xbe\x01\n" +
	"\rGetEmailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x16\n" +
	"\x06userid\x18\x05 \x01(\rR\x06userid\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"*\n" +
	"\x10ListEmailRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\rR\x06userid\"C\n" +
	"\x0eListEmailReply\x121\n" +
	"\x06emails\x18\x01 \x03(\v2\x19.api.helloworld.v1.EmailsR\x06emails\"\xb7\x01\n" +
	"\x06Emails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12\x16\n" +
	"\x06userid\x18\x05 \x01(\rR\x06userid\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt2\xb8\x04\n" +
	"\x05Email\x12o\n" +
	"\vCreateEmail\x12%.api.helloworld.v1.CreateEmailRequest\x1a#.api.helloworld.v1.CreateEmailReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/email\x12t\n" +
	"\vUpdateEmail\x12%.api.helloworld.v1.UpdateEmailRequest\x1a#.api.helloworld.v1.UpdateEmailReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/email/{id}\x12q\n" +
	"\vDeleteEmail\x12%.api.helloworld.v1.DeleteEmailRequest\x1a#.api.helloworld.v1.DeleteEmailReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/email/{id}\x12h\n" +
	"\bGetEmail\x12\".api.helloworld.v1.GetEmailRequest\x1a .api.helloworld.v1.GetEmailReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/email/{id}\x12k\n" +
	"\tListEmail\x12#.api.helloworld.v1.ListEmailRequest\x1a!.api.helloworld.v1.ListEmailReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/email/listB?\n" +
	"\x11api.helloworld.v1P\x01Z(customer-management/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_email_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_email_proto_rawDescData []byte
)

func file_api_helloworld_v1_email_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_email_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_email_proto_rawDesc), len(file_api_helloworld_v1_email_proto_rawDesc)))
	})
	return file_api_helloworld_v1_email_proto_rawDescData
}

var file_api_helloworld_v1_email_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_helloworld_v1_email_proto_goTypes = []any{
	(*CreateEmailRequest)(nil), // 0: api.helloworld.v1.CreateEmailRequest
	(*CreateEmailReply)(nil),   // 1: api.helloworld.v1.CreateEmailReply
	(*UpdateEmailRequest)(nil), // 2: api.helloworld.v1.UpdateEmailRequest
	(*UpdateEmailReply)(nil),   // 3: api.helloworld.v1.UpdateEmailReply
	(*DeleteEmailRequest)(nil), // 4: api.helloworld.v1.DeleteEmailRequest
	(*DeleteEmailReply)(nil),   // 5: api.helloworld.v1.DeleteEmailReply
	(*GetEmailRequest)(nil),    // 6: api.helloworld.v1.GetEmailRequest
	(*GetEmailReply)(nil),      // 7: api.helloworld.v1.GetEmailReply
	(*ListEmailRequest)(nil),   // 8: api.helloworld.v1.ListEmailRequest
	(*ListEmailReply)(nil),     // 9: api.helloworld.v1.ListEmailReply
	(*Emails)(nil),             // 10: api.helloworld.v1.Emails
}
var file_api_helloworld_v1_email_proto_depIdxs = []int32{
	10, // 0: api.helloworld.v1.ListEmailReply.emails:type_name -> api.helloworld.v1.Emails
	0,  // 1: api.helloworld.v1.Email.CreateEmail:input_type -> api.helloworld.v1.CreateEmailRequest
	2,  // 2: api.helloworld.v1.Email.UpdateEmail:input_type -> api.helloworld.v1.UpdateEmailRequest
	4,  // 3: api.helloworld.v1.Email.DeleteEmail:input_type -> api.helloworld.v1.DeleteEmailRequest
	6,  // 4: api.helloworld.v1.Email.GetEmail:input_type -> api.helloworld.v1.GetEmailRequest
	8,  // 5: api.helloworld.v1.Email.ListEmail:input_type -> api.helloworld.v1.ListEmailRequest
	1,  // 6: api.helloworld.v1.Email.CreateEmail:output_type -> api.helloworld.v1.CreateEmailReply
	3,  // 7: api.helloworld.v1.Email.UpdateEmail:output_type -> api.helloworld.v1.UpdateEmailReply
	5,  // 8: api.helloworld.v1.Email.DeleteEmail:output_type -> api.helloworld.v1.DeleteEmailReply
	7,  // 9: api.helloworld.v1.Email.GetEmail:output_type -> api.helloworld.v1.GetEmailReply
	9,  // 10: api.helloworld.v1.Email.ListEmail:output_type -> api.helloworld.v1.ListEmailReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_email_proto_init() }
func file_api_helloworld_v1_email_proto_init() {
	if File_api_helloworld_v1_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_email_proto_rawDesc), len(file_api_helloworld_v1_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_email_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_email_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_email_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_email_proto = out.File
	file_api_helloworld_v1_email_proto_goTypes = nil
	file_api_helloworld_v1_email_proto_depIdxs = nil
}
