// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/helloworld/v1/address/address.proto

package address

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. permanant, temporary
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressData) Reset() {
	*x = AddressData{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressData) ProtoMessage() {}

func (x *AddressData) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressData.ProtoReflect.Descriptor instead.
func (*AddressData) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *AddressData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressData) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *AddressData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddressData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AddressData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,2,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g. permanant, temporary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressReply) Reset() {
	*x = CreateAddressReply{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressReply) ProtoMessage() {}

func (x *CreateAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressReply.ProtoReflect.Descriptor instead.
func (*CreateAddressReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAddressReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAddressReply) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateAddressReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. permanant, temporary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateAddressRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *UpdateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type UpdateAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. permanant, temporary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressReply) Reset() {
	*x = UpdateAddressReply{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressReply) ProtoMessage() {}

func (x *UpdateAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressReply.ProtoReflect.Descriptor instead.
func (*UpdateAddressReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAddressReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateAddressReply) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *UpdateAddressReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressReply) Reset() {
	*x = DeleteAddressReply{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressReply) ProtoMessage() {}

func (x *DeleteAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressReply.ProtoReflect.Descriptor instead.
func (*DeleteAddressReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAddressReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{7}
}

func (x *GetAddressRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Pincode       string                 `protobuf:"bytes,3,opt,name=pincode,proto3" json:"pincode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // e.g. permanant, temporary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressReply) Reset() {
	*x = GetAddressReply{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressReply) ProtoMessage() {}

func (x *GetAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressReply.ProtoReflect.Descriptor instead.
func (*GetAddressReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{8}
}

func (x *GetAddressReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetAddressReply) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *GetAddressReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressRequest) Reset() {
	*x = ListAddressRequest{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressRequest) ProtoMessage() {}

func (x *ListAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressRequest.ProtoReflect.Descriptor instead.
func (*ListAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{9}
}

type ListAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []*AddressData         `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddressReply) Reset() {
	*x = ListAddressReply{}
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddressReply) ProtoMessage() {}

func (x *ListAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_address_address_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddressReply.ProtoReflect.Descriptor instead.
func (*ListAddressReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_address_address_proto_rawDescGZIP(), []int{10}
}

func (x *ListAddressReply) GetAddress() []*AddressData {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_api_helloworld_v1_address_address_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_address_address_proto_rawDesc = "" +
	"\n" +
	"'api/helloworld/v1/address/address.proto\x12\x19api.helloworld.v1.address\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n" +
	"\vAddressData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"^\n" +
	"\x14CreateAddressRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x02 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"l\n" +
	"\x12CreateAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"n\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"l\n" +
	"\x12UpdateAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"&\n" +
	"\x14DeleteAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\".\n" +
	"\x12DeleteAddressReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"i\n" +
	"\x0fGetAddressReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\apincode\x18\x03 \x01(\tR\apincode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\x14\n" +
	"\x12ListAddressRequest\"T\n" +
	"\x10ListAddressReply\x12@\n" +
	"\aaddress\x18\x01 \x03(\v2&.api.helloworld.v1.address.AddressDataR\aaddress2\xb7\x05\n" +
	"\aAddress\x12\x87\x01\n" +
	"\rCreateAddress\x12/.api.helloworld.v1.address.CreateAddressRequest\x1a-.api.helloworld.v1.address.CreateAddressReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/address\x12\x8c\x01\n" +
	"\rUpdateAddress\x12/.api.helloworld.v1.address.UpdateAddressRequest\x1a-.api.helloworld.v1.address.UpdateAddressReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/address/{id}\x12\x89\x01\n" +
	"\rDeleteAddress\x12/.api.helloworld.v1.address.DeleteAddressRequest\x1a-.api.helloworld.v1.address.DeleteAddressReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/address/{id}\x12\x80\x01\n" +
	"\n" +
	"GetAddress\x12,.api.helloworld.v1.address.GetAddressRequest\x1a*.api.helloworld.v1.address.GetAddressReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/address/{id}\x12\x83\x01\n" +
	"\vListAddress\x12-.api.helloworld.v1.address.ListAddressRequest\x1a+.api.helloworld.v1.address.ListAddressReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/address/listBT\n" +
	"\x19api.helloworld.v1.addressP\x01Z5customer-management/api/helloworld/v1/address;addressb\x06proto3"

var (
	file_api_helloworld_v1_address_address_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_address_address_proto_rawDescData []byte
)

func file_api_helloworld_v1_address_address_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_address_address_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_address_address_proto_rawDesc), len(file_api_helloworld_v1_address_address_proto_rawDesc)))
	})
	return file_api_helloworld_v1_address_address_proto_rawDescData
}

var file_api_helloworld_v1_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_helloworld_v1_address_address_proto_goTypes = []any{
	(*AddressData)(nil),          // 0: api.helloworld.v1.address.AddressData
	(*CreateAddressRequest)(nil), // 1: api.helloworld.v1.address.CreateAddressRequest
	(*CreateAddressReply)(nil),   // 2: api.helloworld.v1.address.CreateAddressReply
	(*UpdateAddressRequest)(nil), // 3: api.helloworld.v1.address.UpdateAddressRequest
	(*UpdateAddressReply)(nil),   // 4: api.helloworld.v1.address.UpdateAddressReply
	(*DeleteAddressRequest)(nil), // 5: api.helloworld.v1.address.DeleteAddressRequest
	(*DeleteAddressReply)(nil),   // 6: api.helloworld.v1.address.DeleteAddressReply
	(*GetAddressRequest)(nil),    // 7: api.helloworld.v1.address.GetAddressRequest
	(*GetAddressReply)(nil),      // 8: api.helloworld.v1.address.GetAddressReply
	(*ListAddressRequest)(nil),   // 9: api.helloworld.v1.address.ListAddressRequest
	(*ListAddressReply)(nil),     // 10: api.helloworld.v1.address.ListAddressReply
}
var file_api_helloworld_v1_address_address_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.v1.address.ListAddressReply.address:type_name -> api.helloworld.v1.address.AddressData
	1,  // 1: api.helloworld.v1.address.Address.CreateAddress:input_type -> api.helloworld.v1.address.CreateAddressRequest
	3,  // 2: api.helloworld.v1.address.Address.UpdateAddress:input_type -> api.helloworld.v1.address.UpdateAddressRequest
	5,  // 3: api.helloworld.v1.address.Address.DeleteAddress:input_type -> api.helloworld.v1.address.DeleteAddressRequest
	7,  // 4: api.helloworld.v1.address.Address.GetAddress:input_type -> api.helloworld.v1.address.GetAddressRequest
	9,  // 5: api.helloworld.v1.address.Address.ListAddress:input_type -> api.helloworld.v1.address.ListAddressRequest
	2,  // 6: api.helloworld.v1.address.Address.CreateAddress:output_type -> api.helloworld.v1.address.CreateAddressReply
	4,  // 7: api.helloworld.v1.address.Address.UpdateAddress:output_type -> api.helloworld.v1.address.UpdateAddressReply
	6,  // 8: api.helloworld.v1.address.Address.DeleteAddress:output_type -> api.helloworld.v1.address.DeleteAddressReply
	8,  // 9: api.helloworld.v1.address.Address.GetAddress:output_type -> api.helloworld.v1.address.GetAddressReply
	10, // 10: api.helloworld.v1.address.Address.ListAddress:output_type -> api.helloworld.v1.address.ListAddressReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_address_address_proto_init() }
func file_api_helloworld_v1_address_address_proto_init() {
	if File_api_helloworld_v1_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_address_address_proto_rawDesc), len(file_api_helloworld_v1_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_address_address_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_address_address_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_address_address_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_address_address_proto = out.File
	file_api_helloworld_v1_address_address_proto_goTypes = nil
	file_api_helloworld_v1_address_address_proto_depIdxs = nil
}
